[package]
name = "donations"
version = "0.0.1"
authors = [ "alex@devaccent.com", ]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.33.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.33.0"
